<?php

/**
 * @file
 * Code for the get_tweets module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_cron().
 */
function get_tweets_cron() {
  \Drupal::service('get_tweets.base')->runAll();
}

/**
 * Implementation of hook_redirect_node_view().
 */
function get_tweets_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface && $node->bundle() == 'tweet') {
    $url = vsprintf('https://twitter.com/%s/status/%s', [
      $node->field_tweet_author->title,
      $node->field_tweet_id->value,
    ]);

    $response = new RedirectResponse($url);
    $response->send();
    return;
  }
}

/**
 * Implements hook_update_N().
 */
function get_tweets_update_8001(&$sandbox) {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('get_tweets.settings');

  $data = $config->getRawData();
  $queries = [];

  if (!isset($data['usernames'])) {
    return;
  }

  foreach ($data['usernames'] as $id => $query) {
    $queries[$id]['query'] = $query;

    if (strpos($query, '@') === 0) {
      $queries[$id]['endpoint'] = 'statuses/user_timeline';
      $queries[$id]['parameter'] = 'screen_name';
    }
    else {
      $queries[$id]['endpoint'] = 'search/tweets';
      $queries[$id]['parameter'] = 'q';
    }

  }

  $data['queries'] = $queries;

  unset($data['usernames']);

  $config->setData($data);
  $config->save(TRUE);
}
